### ISSUE TITLE
服务端问题

### ISSUE THREAD

**Issue by 18398639574** [SuperJolly/wxapp-little-shelf#4]
如若已在管理后台更新域名配置，请刷新项目配置后重新编译项目，操作路径：“详情-域名信息”
VM54:1  http://127.0.0.1 不在以下 request 合法域名列表中，请参考文档：https://developers.weixin.qq.com/miniprogram/dev/framework/ability/network.html
console.error @ VM54:1
n @ appservice?t=1542514814053:1209
h @ appservice?t=1542514814053:1209
createRequestTask @ appservice?t=1542514814053:1209
invoke @ appservice?t=1542514814053:1209
o @ WAService.js:4
u @ WAService.js:4
r @ WAService.js:10
e @ WAService.js:10
(anonymous) @ WAService.js:10
(anonymous) @ WAService.js:4
success @ app.js? [sm]:65
(anonymous) @ WAService.js:3
u @ WAService.js:4
(anonymous) @ WAService.js:4
function.setTimeout @ appservice?t=1542514814053:1209
(anonymous) @ WAService.js:3
(anonymous) @ WAService.js:8
setTimeout (async)
setTimeout @ WAService.js:8
v @ appservice?t=1542514814053:1209
r.registerCallback.t @ appservice?t=1542514814053:1209
l.forEach.t @ appservice?t=1542514814053:1209
(anonymous) @ appservice?t=1542514814053:1209
s.onmessage @ appservice?t=1542514814053:1209
appservice?t=1542514814053:1209

**Comment by SuperJolly** [comment]
![image](https://user-images.githubusercontent.com/13775060/48690395-4ae23680-ec09-11e8-851c-26a42ccaf609.png)
开启上面选项重新编译
